import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar.jsx"
import Main from "../components/Main.jsx"
export default function Home() {
  return (
    <div >
      <Head>
        <title>Simon Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />


    </div>
  )
}
